pub struct Solution {}

impl Solution {
    #[allow(dead_code)]
    pub fn solve() {}
}

mod s0001_two_sum;
mod s0002_add_two_numbers;
mod s0003_longest_substring_without_repeating_characters;
mod s0004_median_of_two_sorted_arrays;
mod s0005_longest_palindromic_substring;
mod s0006_zigzag_conversion;
mod s0007_reverse_integer;
mod s0008_string_to_integer_atoi;
mod s0009_palindrome_number;
mod s0010_regular_expression_matching;
mod s0011_container_with_most_water;
mod s0012_integer_to_roman;
mod s0013_roman_to_integer;
mod s0014_longest_common_prefix;
mod s0015_3sum;
mod s0016_3sum_closest;
mod s0017_letter_combinations_of_a_phone_number;
mod s0019_remove_nth_node_from_end_of_list;
mod s0020_valid_parentheses;
mod s0021_merge_two_sorted_lists;
mod s5697_check_if_binary_string_has_at_most_one_segment_of_ones;
mod s5698_minimum_elements_to_add_to_form_a_given_sum;
mod s5699_number_of_restricted_paths_from_first_to_last_node;
mod s5701_check_if_one_string_swap_can_make_strings_equal;
mod s5702_find_center_of_star_graph;
mod s5703_maximum_average_pass_ratio;
mod s5704_maximum_score_of_a_good_subarray;
mod s5709_maximum_ascending_subarray_sum;
mod s5710_number_of_orders_in_the_backlog;
mod s5711_maximum_value_at_a_given_index_in_a_bounded_array;
mod s5722_truncate_sentence;
mod s5723_finding_the_users_active_minutes;
mod s5724_minimum_absolute_sum_difference;
mod s5725_number_of_different_subsequences_gcds;
mod s5734_check_if_the_sentence_is_pangram;
mod s5735_maximum_ice_cream_bars;
mod s5738_sum_of_digits_in_base_k;
mod s5739_frequency_of_the_most_frequent_element;
mod s5740_longest_substring_of_all_vowels_in_order;
mod s5746_minimum_distance_to_the_target_element;
mod s5747_splitting_a_string_into_descending_consecutive_values;
mod s5750_maximum_population_year;
mod s5751_maximum_distance_between_a_pair_of_values;
mod s5752_maximum_subarray_min_product;
mod s5788_largest_odd_number_in_string;
mod utility;
